"""Second time migration

Revision ID: 3b477a1b2b4c
Revises: cf733347c21b
Create Date: 2021-05-27 11:10:17.967349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b477a1b2b4c'
down_revision = 'cf733347c21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserCredential', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserCredential', 'Password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('UserCredential', 'PhoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserCredential', sa.Column('PhoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('UserCredential', 'Password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserCredential', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
