"""Second Migration with FK removed on Event

Revision ID: b82891997dea
Revises: 3c933bef9f19
Create Date: 2021-05-29 18:20:17.719778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82891997dea'
down_revision = '3c933bef9f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Event_CreatedBy_fkey', 'Event', type_='foreignkey')
    op.drop_column('Event', 'CreatedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('CreatedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Event_CreatedBy_fkey', 'Event', 'User', ['CreatedBy'], ['UserId'])
    # ### end Alembic commands ###
