from eshiBlood.resources.admin.appointments.appointments import appointment_admin_ns
from eshiBlood.resources.admin.donation_centers.donation_centers import donation_centers_admin_ns
from eshiBlood.resources.admin.events.events import event_admin_ns
from eshiBlood.resources.admin.requests.requests import request_admin_ns
